version: 2
updates:
  # Routine Cargo updates → develop
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    target-branch: develop
    labels: [deps, cargo]
    open-pull-requests-limit: 10
    groups:
      routine:
        update-types: [minor, patch]

  # Routine GitHub Actions updates → develop
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: develop
    labels: [deps, ci]
    open-pull-requests-limit: 10
