[git]
# Match tags like v0.1.6
tag_pattern = "^v\\d+\\.\\d+\\.\\d+$"

# Optional: rewrite merge commit messages to a neat "PR #123: Title"
commit_preprocessors = [
  { pattern = "(?s)Merge pull request #(\\d+) from [^\\n]+\\n\\n(.+)", replace = "PR #$1: $2" }
]

# Group commit messages
[[git.commit_parsers]]
message = "^feat"
group = "Features"

[[git.commit_parsers]]
message = "^fix"
group = "Fixes"

[[git.commit_parsers]]
message = "^perf"
group = "Performance"

[[git.commit_parsers]]
message = "^refactor"
group = "Refactoring"

[[git.commit_parsers]]
message = "^docs"
group = "Docs"

[[git.commit_parsers]]
message = "^ci"
group = "CI"

[[git.commit_parsers]]
message = "^chore"
group = "Chore"

[[git.commit_parsers]]
message = "^test"
group = "Tests"

# Merge commits detected as PRs
[[git.commit_parsers]]
message = "(?i)Merge pull request #(\\d+)"
group = "Merged PRs"

# Catch-all
[[git.commit_parsers]]
message = ".*"
group = "Other"

[changelog]
header = """# Changelog
"""
body = """
{% for group, commits in commits | group_by(attribute="group") -%}
### {{ group }}
{%- for commit in commits %}
- {{ commit.subject }} ({{ commit.hash | truncate(length=7, end="") }})
{%- endfor %}

{%- endfor -%}
"""
footer = """
Generated by git-cliff.
"""
