[git]
# Match tags like v0.1.6
tag_pattern = "^v\\d+\\.\\d+\\.\\d+$"
# We don't force Conventional Commits; messages still work fine.
conventional_commits = false

# Normalize merge commits into a single-line title
commit_preprocessors = [
  { pattern = "(?s)Merge pull request #(\\d+) from [^\\n]+\\n\\n(.+)", replace = "PR #$1: $2" }
]

# Grouping rules (tweak as you like)
[[git.commit_parsers]]
message = "^feat"
group = "Features"

[[git.commit_parsers]]
message = "^fix"
group = "Fixes"

[[git.commit_parsers]]
message = "^perf"
group = "Performance"

[[git.commit_parsers]]
message = "^refactor"
group = "Refactoring"

[[git.commit_parsers]]
message = "^docs"
group = "Docs"

[[git.commit_parsers]]
message = "^ci"
group = "CI"

[[git.commit_parsers]]
message = "^chore"
group = "Chore"

[[git.commit_parsers]]
message = "^test"
group = "Tests"

# Merge commits detected as PRs
[[git.commit_parsers]]
message = "(?i)^merge pull request #(\\d+)"
group = "Merged PRs"

# Catch-all
[[git.commit_parsers]]
message = ".*"
group = "Other"

[changelog]
header = """# Changelog
"""

# Render each release grouped by our parser groups
body = """
{% for group, commits in commits | group_by(attribute="group") -%}
### {{ group }}
{%- for commit in commits %}
- {{ commit.message | split(pat="\\n") | first }} ({{ commit.id | truncate(length=7, end="") }})
{%- endfor %}

{%- endfor -%}
"""

footer = """
Generated by git-cliff.
"""
