# cliff.toml — tailored for chd2iso-fuse
[git]
conventional_commits = true
filter_unconventional = false
tag_pattern = "v[0-9]*"
topo_order = true

commit_parsers = [
  # PR merges (most important)
  { message = "(?s)^Merge pull request #(?P<pr>\\d+).*\\n\\n(?P<title>.+)$",
    group = "Merged PRs",
    body = "PR #{{pr}} — {{title}}" },

  # Conventional commits (fallback for direct pushes)
  { message = "^feat",      group = "Features" },
  { message = "^fix",       group = "Fixes" },
  { message = "^perf",      group = "Performance" },
  { message = "^refactor",  group = "Refactor" },
  { message = "^docs",      group = "Docs" },
  { message = "^build|^ci", group = "Build & CI" },
  { message = "^chore|^style", group = "Chore" },

  # Catch-all
  { message = ".*", group = "Other" },
]

[remote]
github = "lloydsmart/chd2iso-fuse"

[changelog]
header = """
# Changelog
All notable changes to this project will be documented here.
"""

body = """
{% if version %}## {{ version }} — {{ timestamp | date(format="%Y-%m-%d") }}{% else %}## Unreleased{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.body | default(value=commit.message | first_line) }} ({{ commit.hash | truncate(length=7, end="") }})
{% endfor %}

{% endfor %}
"""

footer = """
---
Generated by [git-cliff](https://github.com/orhun/git-cliff).
"""

trim = true
