# cargo-deny policy
# Docs: https://embarkstudios.github.io/cargo-deny/

########################################
# Advisories
########################################
[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]

ignore = [
  { id = "RUSTSEC-2021-0154", reason = "fuser has no fixed release; project does not process untrusted inputs" },
]

# Scope/levels for other advisory classes
unmaintained = "workspace"  # one of: all | workspace | transitive | none
yanked       = "warn"       # one of: deny | warn | allow
# git-fetch-with-cli = true

########################################
# Licenses
########################################
[licenses]
# Allow common permissive + Unicode licenses used by deps
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "Unicode-3.0",      # needed by unicode-ident’s "(MIT OR Apache-2.0) AND Unicode-3.0"
  "Zlib",
]

confidence-threshold = 0.8
unused-allowed-license = "warn"   # <— correct key; avoid failing on unused allows

########################################
# Bans (optional hygiene)
########################################
[bans]
multiple-versions = "warn"
wildcards = "deny"
