# cargo-deny policy
# Docs: https://embarkstudios.github.io/cargo-deny/

########################################
# Advisories
########################################
[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]

ignore = [
  { id = "RUSTSEC-2021-0154", reason = "fuser has no fixed release; project does not process untrusted inputs" },
]

# advisory classes handling
unmaintained = "workspace"
yanked       = "warn"
# git-fetch-with-cli = true

########################################
# Licenses
########################################
[licenses]
# Allow common permissive licenses + Unicode licenses used by deps
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "Unicode-3.0",          # <-- needed for unicode-ident's "(MIT OR Apache-2.0) AND Unicode-3.0"
  "Zlib",
]
confidence-threshold = 0.8
unused-allowed = "warn"   # don't fail just because an allowed license isn't currently encountered

########################################
# Bans (optional hygiene)
########################################
[bans]
multiple-versions = "warn"
wildcards = "deny"
