# cargo-deny policy
# Docs: https://embarkstudios.github.io/cargo-deny/

########################################
# Advisories
########################################
[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]

ignore = [
  { id = "RUSTSEC-2021-0154", reason = "fuser has no fixed release; project does not process untrusted inputs" },
]

# Scope/levels for other advisory classes
unmaintained = "workspace"  # one of: all | workspace | transitive | none
yanked       = "warn"       # one of: deny | warn | allow
# git-fetch-with-cli = true

########################################
# Licenses
########################################
# ---------------------------------------------------------------------
# cargo-deny license policy
#
# The "allow" list should only include licenses actually in use.
# To review current licenses in the dependency tree, run:
#
#   cargo deny list
#
# If new licenses appear in your dependencies, you can add them here.
# Avoid leaving unused licenses in the list, as this causes
# `license-not-encountered` warnings in CI.
# ---------------------------------------------------------------------

[licenses]
# Allow any OSI-approved and FSF-free license (includes GPL, LGPL, MPL, EPL, etc.)
allow-osi-fsf-free = "both"

# Explicit allowlist still applies alongside the OSI/FSF rule.
# These are the main licenses we actively expect in this project.
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
]

# Fail on unlicensed or unknown licenses
default = "deny"
unlicensed = "deny"

confidence-threshold = 0.8
unused-allowed-license = "warn"

########################################
# Bans (optional hygiene)
########################################
[bans]
multiple-versions = "warn"
wildcards = "deny"
