# cargo-deny policy
# Docs: https://embarkstudios.github.io/cargo-deny/

########################################
# Advisories
########################################
[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]

ignore = [
  { id = "RUSTSEC-2021-0154", reason = "fuser has no fixed release; project does not process untrusted inputs" },
]

# Scope/levels for other advisory classes
unmaintained = "workspace"  # one of: all | workspace | transitive | none
yanked       = "warn"       # one of: deny | warn | allow
# git-fetch-with-cli = true

########################################
# Licenses
########################################
# ---------------------------------------------------------------------
# cargo-deny license policy
#
# The "allow" list should only include licenses actually in use.
# To review current licenses in the dependency tree, run:
#
#   cargo deny list
#
# If new licenses appear in your dependencies, you can add them here.
# Avoid leaving unused licenses in the list, as this causes
# `license-not-encountered` warnings in CI.
#
# Docs: https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
# ---------------------------------------------------------------------

[licenses]
# Allow any OSI/FSF-free licenses by explicitly listing the ones we accept.
# GNU-family and some niche licenses must be listed explicitly on cargo-deny ≥ 0.18.

allow = [
  # Permissive
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Zlib",            # ← needed by foldhash, zlib-rs, libz-rs-sys

  # Unicode data license (used by unicode-ident)
  "Unicode-3.0",     # ← needed for (MIT OR Apache-2.0) AND Unicode-3.0

  # Copyleft (kept allowed so GPL/LGPL crates won’t block CI if introduced)
  "GPL-2.0-or-later",
  "GPL-3.0-or-later",
  "LGPL-2.1-or-later",
  "LGPL-3.0-or-later",

  # Other common FOSS licenses (okay to keep even if not currently used)
  "MPL-2.0",
  "EPL-2.0"
]

# Keep the detector strict enough to be useful
confidence-threshold = 0.8

# Don’t fail CI if something is left in allow but not currently used
unused-allowed-license = "warn"

# (Optional) If you need to allow a license for a single crate only:
# [[licenses.exceptions]]
# crate = "some-crate"
# allow = ["CDDL-1.0"]


########################################
# Bans (optional hygiene)
########################################
[bans]
multiple-versions = "warn"
wildcards = "deny"
