.\"                                      -*- nroff -*-
.TH UMOUNT.CHD2ISO-FUSE 8 "August 2025" "chd2iso-fuse" "System Administration"
.SH NAME
umount.chd2iso-fuse \- helper to unmount CHD images mounted via FUSE
.SH SYNOPSIS
.B umount.chd2iso-fuse
.I mountpoint
.SH DESCRIPTION
The
.B umount.chd2iso-fuse
program is a convenience wrapper that invokes
.BR umount (8)
to detach a filesystem previously mounted with
.BR mount.chd2iso-fuse (8) .
.SH SEE ALSO
.BR chd2iso-fuse (1),
.BR umount (8),
.BR mount.chd2iso-fuse (8)
