name: Lint & Build (Debian Trixie)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
      options: --init
    permissions:
      contents: read
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain & build deps
        run: |
          set -e
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential pkg-config \
            libfuse3-dev fuse3 \
            rustc cargo rustfmt rust-clippy clang \
            devscripts debhelper dh-cargo lintian ca-certificates git
          update-ca-certificates

      - name: Cache Cargo (registry, git, target)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-trixie-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-trixie-cargo-

      - name: Cargo fmt (check)
        run: cargo fmt -- --check

      - name: Cargo clippy (deny warnings)
        run: cargo clippy -- -D warnings

      - name: Build release (cargo)
        run: cargo build --release

      - name: Build .deb (debuild)
        run: debuild -us -uc -b

      - name: Lintian (non-fatal)
        run: |
          set -e
          # Lint the build if present (ignore return to avoid failing PRs on advisories)
          if ls ../chd2iso-fuse_*_amd64.changes >/dev/null 2>&1; then
            lintian ../chd2iso-fuse_*_amd64.changes || true
          fi

      - name: Collect Debian artifacts
        run: |
          set -e
          mkdir -p artifacts
          for f in \
            ../chd2iso-fuse_*_amd64.deb \
            ../chd2iso-fuse-dbgsym_*_amd64.deb \
            ../chd2iso-fuse_*_amd64.buildinfo \
            ../chd2iso-fuse_*_amd64.changes
          do
            [ -e "$f" ] && mv "$f" artifacts/
          done
          ls -al artifacts || true

      - name: Upload Debian artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chd2iso-fuse-debs
          path: artifacts/*
          if-no-files-found: error
          retention-days: 14
