name: CI Router (git-flow)

on:
  push:
    branches: [ "**" ]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "build.rs"
      - "debian/**"
      - ".github/workflows/**"
      - "Makefile"
  pull_request:
    branches: [ develop, main ]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "build.rs"
      - "debian/**"
      - ".github/workflows/**"
      - "Makefile"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  decide:
    name: Decide lane
    runs-on: ubuntu-latest
    outputs:
      lane: ${{ steps.which.outputs.lane }}
    steps:
      - id: which
        shell: bash
        run: |
          ref="${GITHUB_REF_NAME}"
          lane="feature"
          case "$ref" in
            develop) lane="develop" ;;
            main)    lane="main" ;;
          esac
          [[ "$ref" == release/* ]] && lane="release"
          [[ "$ref" == hotfix/*  ]] && lane="hotfix"
          echo "lane=$lane" >> "$GITHUB_OUTPUT"

  build:
    name: Build & Test
    uses: ./.github/workflows/_build.yml
    with:
      lane: ${{ needs.decide.outputs.lane }}
    secrets: inherit
    needs: decide

  release:
    if: ${{ needs.decide.outputs.lane != 'feature' && success() && github.event_name != 'pull_request' }}
    name: Release lane (gated)
    permissions:
      contents: write
    uses: ./.github/workflows/_release.yml
    with:
      lane: ${{ needs.decide.outputs.lane }}
      apt_enabled: false
    secrets: inherit
    needs: [decide, build]
