name: CI (snapshot .deb for testing)

on:
  push:
    branches: [ main ]
    tags-ignore: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-deb:
    name: Build Debian package (snapshot) — trixie
    runs-on: ubuntu-latest
    container: debian:trixie

    steps:
      - name: Install base tools
        run: |
          apt-get update
          apt-get install -y git ca-certificates curl

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps (Debian trixie)
        run: |
          apt-get update
          apt-get install -y \
            debhelper devscripts dh-cargo fakeroot \
            build-essential pkg-config \
            fuse3 libfuse3-dev \
            rustc cargo

      - name: Show toolchain
        run: |
          rustc --version
          cargo --version
          dpkg -l | egrep 'fuse3|libfuse3|debhelper|dh-cargo|devscripts' || true

      - name: Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            /github/home/.cargo/registry
            /github/home/.cargo/git
            target
          key: ${{ runner.os }}-debian-trixie-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-debian-trixie-cargo-

      - name: Lint (fmt + clippy)
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Build (sanity)
        run: cargo build --release

      - name: Build .deb (unsigned)
        run: |
          debuild -us -uc -b
          mkdir -p dist
          # Copy all produced artifacts (portable; no 'shopt')
          find .. -maxdepth 1 -type f \( -name 'chd2iso-fuse_*' -o -name 'chd2iso-fuse-*.build' -o -name 'chd2iso-fuse-*.changes' -o -name 'chd2iso-fuse-*.dsc' \) -exec cp -v {} dist/ \;
          # For snapshot job, rename .deb with short SHA
          if [ "${GITHUB_REF##refs/tags/}" = "${GITHUB_REF}" ]; then
            SHORT_SHA="${GITHUB_SHA::7}"
            for f in dist/*.deb; do
              [ -e "$f" ] || continue
              base="$(basename "$f")"
              mv -v "$f" "dist/${base%.deb}-snapshot-${SHORT_SHA}.deb"
            done
          fi
          ls -l dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-snapshot-debian-trixie-${{ github.run_number }}
          path: dist/*
          if-no-files-found: error
          retention-days: 30
