name: Lint & Build (Debian Trixie)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
      options: --init
    steps:
      - uses: actions/checkout@v4

      # --- Cache Cargo (dependencies + build artifacts) ---
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      # --- Toolchain & packaging deps inside the Debian container ---
      - name: Install toolchain & build deps
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential pkg-config \
            libfuse3-dev fuse3 \
            rustc cargo rustfmt rust-clippy clang \
            devscripts debhelper dh-cargo lintian

      # --- Lints ---
      - name: Cargo fmt (check)
        run: cargo fmt -- --check

      - name: Cargo clippy (deny warnings)
        run: cargo clippy -- -D warnings

      # --- Build the binary (benefits from cache) ---
      - name: Build release
        run: cargo build --release

      # --- Build the .deb ---
      - name: Build .deb with debuild
        run: |
          debuild -us -uc -b

      # --- Lint the produced changes file ---
      - name: Lintian
        run: |
          set -e
          # Lintian against the generated .changes (if present)
          CHANGES_FILE=$(ls -1 ../chd2iso-fuse_*_amd64.changes | tail -n1)
          if [ -n "$CHANGES_FILE" ]; then
            lintian "$CHANGES_FILE" || true
          else
            echo "No .changes file found; skipping lintian."
          fi

      # --- Gather artifacts into a safe path (no ..) and upload ---
      - name: Collect Debian artifacts
        run: |
          set -e
          mkdir -p artifacts
          for f in ../chd2iso-fuse_*_amd64.deb \
                   ../chd2iso-fuse-dbgsym_*_amd64.deb \
                   ../chd2iso-fuse_*_amd64.buildinfo \
                   ../chd2iso-fuse_*_amd64.changes; do
            [ -e "$f" ] && cp "$f" artifacts/
          done
          ls -l artifacts

      - name: Upload Debian artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chd2iso-fuse-debs
          path: artifacts/*
          if-no-files-found: error
          retention-days: 14
