name: Lint & Build (Debian Trixie)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
      options: --init
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain & build deps
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential pkg-config \
            libfuse3-dev fuse3 \
            rustc cargo rustfmt rust-clippy clang \
            devscripts debhelper dh-cargo lintian

      - name: Cargo fmt (check)
        run: cargo fmt -- --check

      - name: Cargo clippy (deny warnings)
        run: cargo clippy -- -D warnings

      - name: Build release
        run: cargo build --release

      - name: Build .deb
        run: |
          debuild -us -uc -b
          ls -l ../chd2iso-fuse_*_amd64.deb

      - name: Lintian
        run: |
          lintian ../chd2iso-fuse_*_amd64.changes || true

      - name: Upload artifact (.deb + changes)
        uses: actions/upload-artifact@v4
        with:
          name: chd2iso-fuse-deb
          path: |
            ../chd2iso-fuse_*_amd64.deb
            ../chd2iso-fuse_*_amd64.changes
            ../chd2iso-fuse_*_amd64.buildinfo
