name: Release on tag

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      lane: main
    secrets: inherit

  release:
    needs: build
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
    with:
      lane: main
      apt_enabled: false  # flip later
    secrets: inherit
