name: Release (.deb for Debian trixie)

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write  # needed to create releases & upload assets

jobs:
  release-deb:
    name: Build & publish release assets — trixie
    runs-on: ubuntu-latest
    container: debian:trixie

    steps:
      - name: Install base tools
        run: |
          apt-get update
          apt-get install -y git ca-certificates curl

      - name: Checkout (full history so debuild can read version/changelog)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build deps (Debian trixie)
        run: |
          apt-get update
          apt-get install -y \
            debhelper devscripts dh-cargo fakeroot \
            build-essential pkg-config \
            fuse3 libfuse3-dev \
            rustc cargo

      - name: Toolchain info
        run: |
          rustc --version
          cargo --version

      - name: Cargo cache
        uses: actions/cache@v4
        with:
          path: |
            /github/home/.cargo/registry
            /github/home/.cargo/git
            target
          key: ${{ runner.os }}-debian-trixie-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-debian-trixie-cargo-

      - name: Lint (fmt + clippy)
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Build .deb (unsigned)
        run: |
          debuild -us -uc -b
          mkdir -p dist
          shopt -s nullglob
          for f in ../chd2iso-fuse_*; do
            cp -v "$f" dist/
          done
          ls -l dist

      - name: Create GitHub Release & upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.deb
            dist/*.changes
            dist/*.build
            dist/*.dsc
          generate_release_notes: true
