name: Release (Debian Trixie)

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
      options: --init
    permissions:
      contents: write   # needed to create/upload Release assets
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Install toolchain & build deps
        run: |
          set -e
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential pkg-config \
            libfuse3-dev fuse3 \
            rustc cargo rustfmt rust-clippy clang \
            devscripts debhelper dh-cargo lintian ca-certificates git
          update-ca-certificates

      - name: Cache Cargo (registry, git, target)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-trixie-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-trixie-cargo-

      - name: Cargo fmt (check)
        run: cargo fmt -- --check

      - name: Cargo clippy (deny warnings)
        run: cargo clippy -- -D warnings

      - name: Configure maintainer identity
        run: |
          git config user.name "chd2iso-fuse bot"
          git config user.email "actions@users.noreply.github.com"
        
      - name: Update debian/changelog from tag
        env:
          TAG_REF: ${{ github.ref_name }}
        run: |
          VER="${TAG_REF#v}"
          scripts/update-changelog.sh --release "$VER"
        
      - name: Build .deb (debuild)
        run: debuild -us -uc -b

      - name: Collect Debian artifacts
        run: |
          set -e
          mkdir -p artifacts
          for f in \
            ../chd2iso-fuse_*_amd64.deb \
            ../chd2iso-fuse-dbgsym_*_amd64.deb \
            ../chd2iso-fuse_*_amd64.buildinfo \
            ../chd2iso-fuse_*_amd64.changes
          do
            [ -e "$f" ] && cp "$f" artifacts/
          done
          ls -al artifacts

      - name: Create GitHub Release & upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
